### PR TITLE
Add option to skip pinned messages

### LINKED ISSUE #42: Add option to skip pinned messages
Add a parameter that, if used, will skip deletion of messages that are pinned.

### PR DESCRIPTION
**Pull request by mrrfv**
Fixes #42. This is my first time using Go, so lmk if there's something that needs to be changed/fixed before merging.

### CODE REVIEW

**Comment by cedws** [comment]
Hey, looks good, thank you. Go uses tabs universally so could you change your editor settings? Or you can run `gofmt -s -w .` to autofix.

I am on holiday at the moment so won't be able to merge for a few days.

**Comment by mrrfv** [comment]
`gofmt -s -w .` doesn't seem to do anything. I assume the command intentionally doesn't output anything, but neither Visual Studio Code nor Git doesn't detect any changes.

Could you clone my fork, switch to the `patch-1` branch, and try running the command yourself once your holidays end? Edits by maintainers are enabled, so you should have write access.

**Comment by cedws** [comment]
Actually it's all fine, GitHub mobile is showing the diff a bit strangely. I guess VSCode ran gofmt for you.

I'll get back you soon.

**Comment by cedws** [comment]
Nice feature, thanks again.

**Pull request merged**
